# Problem 1
Bir YetGenli yeni aldığı bahçesinin etrafına çit çevirmek istiyor. Bahçenin etrafını çit ile çevirmek için gerekli çit uzunluğunu ve bahçenin alanını hesaplayan fonksiyonu yazınız.

In [19]:
   def bahce_olculeri(a, b):
    cit_uzunlugu = 2 * (a + b)
    bahce_alani = a * b
    return cit_uzunlugu, bahce_alani

a=50
b=10

cit_uzunlugu, bahce_alani = bahce_olculeri(a, b)
print(f"Çit Uzunluğu: {cit_uzunlugu} metre")
print(f"Bahçe Alanı: {bahce_alani} metrekare")

Çit Uzunluğu: 120 metre
Bahçe Alanı: 500 metrekare

# Problem 2
Kendisine gönderilen 2 sayı arasındaki tüm asal sayıları bulan fonksiyonu yazınız.

In [ ]:
def asal_sayilar(a,b)
    asal_sayilar[]
    for sayi in range (a,b+1)
    if sayi>1:
        for i in range(2,)

# Problem 3
YetGen liderlerinin kurdukları girişim unicorn oluyor. YetGen liderleri iş arkadaşlarının alacağı ücretlerini hesaplamak için bir fonksiyon yazdılar. Bu fonksiyonu kullanarak, YetGen liderlerinin iş arkadaşlarına verecekleri ücretleri hesaplayınız.

Ücret hesaplanması çalışma saatine bağlıdır. Bunun için kullanıcıdan çalışma saati bilgisinn alın. Sonrasında yapılacak ödemenin hesaplanacağı computePay() adlı bir fonksiyon oluşturun. Bu fonksiyonun içinde işlemler yapın. Çalışma saati 40 ve altındaysa saat başına ücret 10 TL’dir. 40 saatin üstünde çalışıldıysa saat başına ücret 15 TL sayılmaktadır.

```
Test etmek için 30 saat değerini giriniz,  sonuç 300 TL çıkmalı, 
ikincil test olarak 50 değerini giriniz,  sonuç 750 TL çıkmalı.
```

In [23]:
çalişma_saati= int(input("Çalışma saatinizi giriniz:") )
def computePay(çalişma_saati):
    if çalişma_saati <= 40:
        ücret= çalişma_saati*10
    elif çalişma_saati >40:
        ücret= çalişma_saati*15
    return ücret

print(f"{çalişma_saati} saat çalışmanın ücreti: {computePay(çalişma_saati)} TL")

50 saat çalışmanın ücreti: 750 TL

# Problem 4
YetGenliler zirveye gitmek için toplanıyor. Zirveye gitmek için kiraladıkları araçlar 4'er kişiliktir. Gelecek kişi sayısı için Airtable üzerinde form açılıyor. Gelecek kişi sayısını alıp dört kişilik araçlara bölüp kalan kişi sayısını döndüren bir fonksiyon yazınız.

In [33]:
gelecek_kisi = int(input("Lütfen gelecek kişi sayısını giriniz: "))

def kalan_kisi(gelecek_kisi):
    kalan= gelecek_kisi %4
    return kalan

kalan = kalan_kisi(gelecek_kisi)
print(f"Kalan kişi sayısı: {kalan}")

TypeError: 'str' object is not callable

# Problem 5
sayiTopla() adında bir fonksiyon yazın. sayiTopla() fonksiyonu girilen sayıları toplayarak yazdırmasını sağlayan bir fonksiyon yazınız.

Örneğin sayiTopla(1,2,3,4,5) yazdığımızda 15 çıktısını almalıyız. sayiTopla(1,2,3,4,5,6,7,8,9,10) yazdığımızda 55 çıktısını almalıyız.

In [35]:
def sayiTopla(*args):
    toplam = sum(args)
    print(f"Girilen sayıların toplamı: {toplam}")

sayiTopla(2,6,5)

TypeError: 'str' object is not callable

# Problem 6

[("xxx",1),("xxx",2),("xxx",9),("xxx",3), ("xxx",1),("xxx",13),("xxx",26),("xxx",4)] listesi içerisinde verilen elemanların her birini tuple içindeki 2. Elemana göre sıralayınız.

In [ ]:
# 6.Problemin Çözümünü Buraya Yazınız

# Problem 7
List comprehension kullanarak 1'den 100'e kadar olan sayılardan sadece çift sayıları bir listeye atmayı yapmayı çalışın.

In [ ]:
# 7.Problemin Çözümünü Buraya Yazınız